DROP TABLE IF EXISTS LVE_RV_HR_ProcessDetail;
-- Crea una tabla nueva
CREATE TABLE IF NOT EXISTS LVE_RV_HR_ProcessDetail (
  -- Identificacion de la tabla
  LVE_RV_HR_ProcessDetail_id NUMERIC(10, 0) PRIMARY KEY,
  LVE_RV_HR_ProcessDetail_uu  CHARACTER VARYING(36) DEFAULT NULL::CHARACTER,
  -- Estos campos son requistos del sistema
  ad_client_id NUMERIC(10, 0) NOT NULL,
  ad_org_id NUMERIC(10, 0) NOT NULL,
  isactive CHARACTER(1) NOT NULL DEFAULT 'Y'::BPCHAR,
  created timestamp WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  createdby NUMERIC(10, 0) NOT NULL,
  updated TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updatedby NUMERIC(10, 0) NOT NULL,
  -- Elementos de la herrameinta,
  Amt NUMERIC(22, 2),
  BPName  CHARACTER VARYING(36) DEFAULT NULL::CHARACTER,
  CategoryValue  CHARACTER VARYING(36) DEFAULT NULL::CHARACTER,
  C_BPartner_ID NUMERIC(10, 0),
  ColumnType BOOLEAN,
  -- Relaciones con otras tablas
  BPTaxID NUMERIC(10, 0), -- Este campo esta en la version de frontuari, pero creo que es la C.I. o RIF
  HR_Concept_Category_ID NUMERIC(10, 0),
  HR_Concept_ID NUMERIC(10, 0),
  HR_Contract_ID NUMERIC(10, 0),
  HR_Departament_ID NUMERIC(10, 0),
  HR_Job_ID NUMERIC(10, 0),
  HR_Movement_ID NUMERIC(10, 0),
  HR_Payroll_ID NUMERIC(10, 0),
  HR_Period_ID NUMERIC(10, 0),
  HR_Process_ID NUMERIC(10, 0),
  LVE_HR_ProcessReport_ID NUMERIC(10, 0),
  -- Descripcion del documento
  SeqNo NUMERIC(10, 0),
  MovDescription CHARACTER VARYING(36) DEFAULT NULL::CHARACTER,
  Name CHARACTER VARYING(36) DEFAULT NULL::CHARACTER,
  Name2 CHARACTER VARYING(36) DEFAULT NULL::CHARACTER,
  Payroll CHARACTER VARYING(36) DEFAULT NULL::CHARACTER,
  PrintName CHARACTER VARYING(36) DEFAULT NULL::CHARACTER,
  ProcessReport CHARACTER VARYING(36) DEFAULT NULL::CHARACTER,
  ReceiptFooterMsg CHARACTER VARYING(36) DEFAULT NULL::CHARACTER,
  TextMsg CHARACTER VARYING(36) DEFAULT NULL::CHARACTER,
  Value CHARACTER VARYING(36) DEFAULT NULL::CHARACTER,
  DocumentNo  CHARACTER VARYING(36) DEFAULT NULL::CHARACTER,
  DocumentNote  CHARACTER VARYING(36) DEFAULT NULL::CHARACTER,
  HeaderPrintName CHARACTER VARYING(36) DEFAULT NULL::CHARACTER,
  -- Fechas
  DateAcct timestamp WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  validfrom TIMESTAMP WITHOUT TIME ZONE,
  validto TIMESTAMP WITHOUT TIME ZONE,
  ServiceDate timestamp WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  ValidFrom timestamp WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  ValidTo timestamp WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
);
